# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload API artifact
      uses: actions/upload-artifact@v3
      with:
        name: PetsEU_API
        path: PetsEU_API/bin/Release/net7.0
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: PetsEU_API
        path: artifacts
    - name: Create release
      run: |
        TAGNAME=${{ github.ref_name }}
        hub release create -a artifacts/* -m "PlanZ $TAGNAME" -t "master" "$TAGNAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
